# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

**NumPY stands for? Ans: Numerical Python  
Numpy developed by? Ans: Travis Oliphant**

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>

# Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`
### Methods: `reshape()`, `max()`, `min()`, `argmax()`, `argmin()`<br>
### Attributes: `size, shape, dtype` 
### Indexing & slicing of 1-D arrays (vectors)
###  Indexing & slicing 2-D arrays (matrices)

In [2]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [6]:
# Lets create a Python list. 
my_list = [-1,0,1] 

my_list

[-1, 0, 1]

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [9]:
my_array = np.array(my_list)

my_array

array([-1,  0,  1])

In [10]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [11]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
matrix_one.shape

(2, 3)

In [13]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [14]:
num = np.arange(100) # similar to range() in Python, not including 100  
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
# We can give the step
np.arange(3,10,2)

array([3, 5, 7, 9])

In [16]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [21]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 20, 100, retstep=True)

(array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
         1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
         2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
         3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
         4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
         5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
         6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
         7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
         8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
         9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
        10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
        11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
        12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
        13.47474747, 13.66666667, 13.85858586, 14.0

In [22]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace
# my_linspace[1] to get the stepsize only

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)

In [23]:
np.linspace(1,15,30) # 1-D array 

array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
        3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
        5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
        8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
       10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
       13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

In [24]:
x = np.arange(0, 16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
x.shape

(16,)

In [36]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
x = x.reshape(2, 4, 2)

In [40]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [41]:
x.shape

(2, 4, 2)

In [48]:
x = x.reshape(16,)

In [49]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
x.shape

(16,)

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [51]:
np.random.rand(5) # 1-D array with three elements

array([0.87083205, 0.08881545, 0.55665684, 0.52820129, 0.18559966])

In [52]:
np.random.rand(6,4)  # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.46365149, 0.25590859, 0.1964071 , 0.01400129],
       [0.83878942, 0.90121687, 0.26977588, 0.46877552],
       [0.99722229, 0.31194416, 0.68470072, 0.749098  ],
       [0.32718649, 0.22761365, 0.98360942, 0.42698578],
       [0.23357051, 0.14017383, 0.16020334, 0.50479897],
       [0.22789672, 0.13816539, 0.48472719, 0.74034865]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [ ]:
np.random.randn(20, 5)

In [ ]:
normal_array = np.random.randn(1000,1) # no tuple, each dimension as a separate argument
normal_array

In [ ]:
import pandas as pd

df = pd.DataFrame(data=normal_array, columns=['A'])
df

In [ ]:
df['A'].hist(bins=100)

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [56]:
np.random.randint(1, 200, 10) #returns one random int, 1 inclusive, 100 exclusive

array([ 37, 180,  95, 132,  77,  16,  37, 147,  44,  56])

In [57]:
np.random.randint(100,500,20).reshape(4,5) #returns ten random int,

array([[341, 384, 201, 324, 232],
       [280, 165, 327, 263, 293],
       [486, 106, 219, 461, 443],
       [164, 253, 402, 368, 234]])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [58]:
# lets create 2 arrays using arange() and randint()
array_ranint = np.random.randint(0,100,10)

In [59]:
array_ranint

array([82,  7, 31,  5, 59, 28, 24, 37, 12, 90])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [ ]:
array_ranint

In [61]:
array_ranint.min()

5

In [60]:
array_ranint.max()

90

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [62]:
array_ranint.argmax() # index starts from 0

9

In [63]:
array_ranint.argmin()

3

### Attributes
* `size, shape, dtype` 

In [64]:
array_arange=np.arange(16)

In [65]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
# Lets take vector array, array_arange 
array_arange.shape
#reshape_test.shape

(16,)

In [67]:
array_arange.size

16

In [68]:
# Size of the array 
array_arange.itemsize

4

In [69]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [70]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
array_arange.shape = (4,4)

In [73]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
array_arange.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [75]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
array_arange.reshape(1,16).shape

### Indexing & slicing of 1-D arrays (vectors)

In [76]:
# Lets create a simple 1-D NumPy array.
# (we can use arange() as well.) 
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [77]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [78]:
# Getting value at certain index
array_1d[2]

0

In [79]:
# Getting a range value
array_1d[0:3]

array([-10,  -2,   0])

In [80]:
# Using -ve index 
array_1d[-2]

106

In [81]:
# Using -ve index for a range 
array_1d[1:-2] 

array([-2,  0,  2, 17])

In [82]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [83]:
array_1d[:2]

array([-10,  -2])

In [84]:
array_1d[2:]

array([  0,   2,  17, 106, 200])

In [85]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102

In [86]:
array_1d
# The first element is changed to -102

array([-102,   -2,    0,    2,   17,  106,  200])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [87]:
array_2d = np.arange(24)
array_2d = array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**. 

We will use `[row,col]`, easier to use comma ',' for clarity.

In [88]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [89]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [90]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [92]:
# another way 
row = 5
column = 2
array_2d[row, column]

22

In [93]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

22

In [94]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [95]:
# 2D array slicing
array_2d[:2,:2] # array_2d[:2,:2].shape gives (2,2), 4 elements for top left corner 

array([[0, 1],
       [4, 5]])

### Broadcasting

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>

**Lets start with some simple examples:**

In [3]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [4]:
array_1d[0:5] = 500 
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [5]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4), dtype=int)
array_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [7]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why?

array([[300, 301, 302, 303],
       [  1,   2,   3,   4],
       [  1,   2,   3,   4],
       [  1,   2,   3,   4]])

In [8]:
array_2d * np.arange(0,4)

array([[  0, 300, 600, 900],
       [  0,   1,   2,   3],
       [  0,   1,   2,   3],
       [  0,   1,   2,   3]])

In [9]:
array_2d + 300
# array_2d + [300,2], did it work? if not why?

array([[600, 600, 600, 600],
       [301, 301, 301, 301],
       [301, 301, 301, 301],
       [301, 301, 301, 301]])

In [10]:
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [11]:
array_2d[[3, 2]]

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
array_2d[:,[2]]

array([[300],
       [  1],
       [  1],
       [  1]])

In [13]:
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [14]:
# We can use any order
array_2d[[3, 1]]

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
# grabbing rows
array_2d[[2,3]] #[2][3]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
array_2d[:3, [2,3]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [18]:
# grabbing columns
#array_2d[:,3:2]
array_2d[:,[3,2]]

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

In [19]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can apply condition such as >, <, == etc

In [20]:
array_1d > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [21]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

Lets create a mask to **filter out the even numbers in "array_1d"**

In [22]:
array_1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [23]:
0 == array_1d % 2

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [24]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = array_1d % 2 != 0 
mod_2_mask_1d

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [25]:
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
array_1d[mod_2_mask_1d] #array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]]

array([1, 3, 5, 7, 9])

## NumPy Operations 

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 2.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>
 

## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [27]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr  

array([0, 1, 2, 3, 4])

In [28]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

In [29]:
# Subtracting two arrays
arr - arr

array([0, 0, 0, 0, 0])

In [30]:
# Multiplication
arr * arr

array([ 0,  1,  4,  9, 16])

In [33]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

C:\Users\ASUS\AppData\Local\Temp\ipykernel_29724\1371265232.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.])

In [32]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

C:\Users\ASUS\AppData\Local\Temp\ipykernel_29724\1491116826.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr #[0, 1, 2, 3, 4]


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [31]:
# Power of all the elements in an array
arr ** 2

array([ 0,  1,  4,  9, 16])

In [34]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [35]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [36]:
# max and min values
np.max(arr), np.min(arr)

(4, 0)

In [37]:
arr.max()

4

In [38]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [ ]:
#18a:
# To avoid overwriting the output, please code here 

In [39]:
array_2d= np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

**Calculate the sum of all the numbers in array_2d?**

In [40]:
array_2d.sum()

435

In [41]:
array_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110, 135])

**Calculate sum of all the rows and columns in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [42]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


**Calculate the standard deviation of the values in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [43]:
array_2d.std()

8.65544144839919

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [44]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [45]:
array_2d % 3 == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [46]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [47]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])